Vagrant::Config.run do |config|
  config.vm.box = ''
  config.vm.box_url = ''
  # config.vm.boot_mode = :gui
  
  # Cloud Stack Management Server
  config.vm.define :cloudstackms do |cloudstackms|  
    cloudstackms.vm.box = ''
    cloudstackms.vm.box_url = ''
    cloudstackms.vm.host_name = 'cloudstackms'
    # Guest Network
    cloudstackms.vm.network :hostonly, "10.10.2.2" 
    # Management Network
    cloudstackms.vm.network :hostonly, "10.10.3.2" 
    # Storage Network
    cloudstackms.vm.network :hostonly, "10.10.4.2" 
    # Public Network
    cloudstackms.vm.network :hostonly, "192.168.3.2"    
    # cloudstackms.vm.customize [
    #   "modifyvm", :id,
    #   "--name", "cloudstackhv",
    #   "--memory", "2048"
    # ]
    cloudstackms.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet-modules/puppet-module-cloudstack']
      puppet.manifest_file = 'site.pp'
      puppet.options = ["--templatedir templates"]
    end
  end

  # Cloud Stack Hypervisor
  config.vm.define :cloudstackhv do |cloudstackhv|  
    cloudstackhv.vm.host_name = 'cloudstackhv'
    # Guest Network
    cloudstackhv.vm.network :hostonly, "10.10.2.3" 
    # Management Network
    cloudstackhv.vm.network :hostonly, "10.10.3.3" 
    # Storage Network
    cloudstackhv.vm.network :hostonly, "10.10.4.3" 
    # Public Network
    cloudstackhv.vm.network :hostonly, "192.168.3.3"
    # cloudstackhv.vm.customize [
    #   "modifyvm", :id,
    #   "--name", "cloudstackhv",
    #   "--memory", "1024"
    # ]
    cloudstackhv.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet-modules/puppet-module-cloudstack']
      puppet.manifest_file = 'site.pp'    
      puppet.options = ["--templatedir templates"]
    end
  end
  
end
